name: alphafold_2.3.2
channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
  - bioconda
dependencies:
  - python==3.10
  - pip 
  - openmm==7.7.0
  - cudnn==8.2.1.32  # Change version if not compatible with current system
  - cudatoolkit==11.0.3  # Change version if not compatible with current system
  - pdbfixer
  - hmmer==3.4
  - hhsuite==3.3.0
  - kalign2==2.04
  - pip:
    - absl-py==1.0.0
    - biopython==1.79 
    - chex==0.0.7 
    - dm-haiku==0.0.10 
    - immutabledict==2.0.0
    - jax==0.4.14 
    - ml-collections==0.1.0  
    - numpy==1.24.3 
    - scipy==1.11.1 
    - tensorflow==2.13.0 
    - pandas==2.0.3 
    - dm-tree==0.1.8 
  - pip3:
    - jax==0.3.25  jaxlib==0.3.25+cuda11.cudnn805 \
      -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html



      
