---
# yamllint disable rule:line-length
format: 1
H5hut:
  defaults:
    group: HDF5
    overlay: base
    relstage: stable
    docfiles: [AUTHORS, COPYING]
    urls:
      - url: https://gitea.psi.ch/H5hut/src/archive/$P-$V.tar.gz

  shasums:
    H5hut-2.0.0rc7.tar.gz: bc058c4817c356b7b7acfe386c586923103b90bdfa83575db3a91754767e6fab
    H5hut-2.0.0rc6.tar.gz: 5aedb48b4cb0530401dd59f3c5ba90f94d0f08e420c4a144594e38eba1df3e48

  versions:
    2.0.0rc7:
      variants:
        - systems: [.*.merlin7.psi.ch]
          overlay: Alps
          relstage: unstable
          group_deps:
            compiler: {gcc: [12.4.0, 13.4.0, 14.3.0, 15.2.0]}
            mpi: {openmpi: [5.0.8]}
            hdf5: {hdf5: [1.14.6]}
          build_requires: []
        - systems: [.*.merlin7.psi.ch]
          overlay: Alps
          relstage: stable
          group_deps:
            compiler: {gcc: [12.3.0, 14.2.0]}
            mpi: {openmpi: [5.0.8]}
            hdf5: {hdf5: [1.14.6]}
          build_requires: []
        - systems: [merlin-.*.psi.ch]
          relstage: unstable
          group_deps:
            compiler: {gcc: [11.5.0]}
            mpi: {openmpi: [4.1.8_slurm]}
            hdf5: {hdf5: [1.14.6]}
          build_requires: []
    2.0.0rc6:
      variants:
        - systems: [merlin-.*.psi.ch]
          relstage: stable
          group_deps:
            compiler: {gcc: [10.4.0]}
            mpi: {openmpi: [4.1.4_slurm, 4.1.5_slurm]}
            hdf5: {hdf5: [1.10.8_slurm]}
          build_requires: []

#Loading module: gcc/10.4.0
#Loading module: openmpi/4.1.5_slurm
#Loading module: hdf5/1.10.8_slurm



#H5hut/2.0.0rc6       stable     gcc/10.3.0 openmpi/4.0.5 hdf5/1.10.7
#H5hut/2.0.0rc6       stable     gcc/10.4.0 openmpi/4.1.4 hdf5/1.10.8
#H5hut/2.0.0rc6       unstable   gcc/10.4.0 openmpi/4.1.5 hdf5/1.10.8
#H5hut/2.0.0rc6_slurm stable     gcc/7.5.0 openmpi/3.1.6_slurm hdf5/1.10.6_slurm
#H5hut/2.0.0rc6_slurm stable     gcc/8.4.0 openmpi/3.1.6_slurm hdf5/1.10.6_slurm
#H5hut/2.0.0rc6_slurm stable     gcc/9.3.0 openmpi/3.1.6_slurm hdf5/1.10.6_slurm
#H5hut/2.0.0rc6_slurm unstable   gcc/9.5.0 openmpi/4.1.5_slurm hdf5/1.10.8_slurm
#H5hut/2.0.0rc6_slurm stable     gcc/10.3.0 openmpi/4.0.5-1_slurm hdf5/1.10.7_slurm
#H5hut/2.0.0rc6_slurm unstable   gcc/11.4.0 openmpi/4.1.5_slurm hdf5/1.10.8_slurm
#H5hut/2.0.0rc6_slurm unstable   gcc/12.3.0 openmpi/4.1.5_slurm hdf5/1.10.8_slurm
#H5hut/2.0.0rc6_slurm unstable   gcc/13.1.0 openmpi/4.1.5_slurm hdf5/1.10.8_slurm
