---
format: 1
membrain:
  defaults:
    group: EM
    overlay: base
    relstage: stable

  versions:
    0.0.1:
      variants:
        - overlay: Alps
          target_cpus: [x86_64]
          systems: [.*.merlin7.psi.ch]
          relstage: stable
