---
# yamllint disable rule:line-length
format: 1
zlib:
  defaults:
    group: Libraries
    overlay: base
    relstage: stable
    urls:
      - url: https://zlib.net/$P-${V_PKG}.tar.gz

  shasums:
    zlib-1.3.1.tar.gz: 9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23

  versions:
    1.3.1:
      variants:
        - overlay: base
          relstage: unstable
