---
# yamllint disable rule:line-length
format: 1
gsl:
  defaults:
    group: Compiler
    overlay: base
    relstage: stable
    urls:
      - url: https://ftp.gnu.org/gnu/$P/$P-$V.tar.gz
    configure_args:
    docfiles:
      - AUTHORS
      - BUGS
      - COPYING
      - ChangeLog
      - INSTALL
      - NEWS
      - README
      - THANKS
      - TODO

  shasums:

  versions:
    2.8:
      config:
          group_deps:
            compiler:
              gcc: [10.5.0, 11.5.0, 12.3.0, 12.4.0, 14.2.0, 14.3.0, 15.2.0]
      variants:
        - systems: [.*.merlin7.psi.ch]
          overlay: PSI
          use_overlays: [PSI]
          relstage: unstable
        - systems: [rhel.*]
          relstage: unstable
