---
# yamllint disable rule:line-length
format: 1
boost:
  defaults:
    group: MPI
    overlay: base
    relstage: stable
    docfiles: [Changelog, Install.txt, LICENSE.txt]
    urls:
      - url: http://glaros.dtc.umn.edu/gkhome/fetch/sw/$P/$P-${V_PKG}.tar.gz 
        name: $P-${V_PKG}.tar.gz

  shasums:

  versions:
    1.86.0:
      config:
        urls:
          - url: https://sourceforge.net/projects/boost/files/boost/1.86.0/boost_1_86_0.tar.gz/download
            name: $P-$V_PKG.tar.gz
      variants:
        - systems: [merlin-.*]
          relstage: unstable
          group_deps:
            compiler:
              gcc: [10.5.0, 11.5.0, 12.4.0, 13.3.0, 14.3.0, 15.2.0]
            mpi:
              openmpi: [4.1.8_slurm]
          build_requires: [zlib/1.3.1]

    1.82.0:
      config:
        urls:
          - url: https://boostorg.jfrog.io/artifactory/main/release/${V_PKG}/source/$P-1_82_0.tar.gz
            name: $P-$V_PKG.tar.gz
      variants:
        - systems: [merlin-.*]
          suffix: _slurm
          group_deps:
            compiler:
              gcc: [9.5.0, 10.4.0, 11.4.0, 12.3.0, 13.1.0]
            mpi:
              openmpi: [4.1.5_slurm]
          build_requires: [zlib/1.2.13]

