---
format: 1
edirect:
  defaults:
    group: EM
    overlay: base
    relstage: stable

  versions:
    24.0:
      variants:
        - overlay: Alps
          systems: [.*.merlin7.psi.ch]
          relstage: stable
